version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: finance_postgres
    restart: always
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: finance_db
    ports:
      - "9379:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
